.TH "A_BLOCK_LINK" 3 "Thu Oct 27 2016" "Version 0.1" "TM4C1294_SensorHub" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A_BLOCK_LINK \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBA_BLOCK_LINK\fP * \fBpxNextFreeBlock\fP"
.br
.ti -1c
.RI "size_t \fBxBlockSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM4C1294_SensorHub from the source code\&.
